defaults:
  - model: spartan
  - data: imagenet
  - _self_

logger_dir: ./logs/metric
checkpoint_dir: ./logs/checkpoints
load_file: null
resume: false

epoch: 300
window: 20
save_freq: 20
log_freq: 30
log_img_limit: 100

distributed: true
use_amp: true

t_initial: 300
init_lr: 2.5e-3
warmup_init_lr: 1e-4
min_lr: 1e-6
warmup_t: 20

weight_decay: 0.03
label_smoothing: 0.2
max_norm: 0.0

seed: 42
